### ISSUE TITLE
Feature request: a safe subset version of this

### ISSUE THREAD

**Issue by simonw** [nalgeon/sqlean.py#1]
This project is _really_ cool! I've been using https://github.com/coleifer/pysqlite3 for a while, but I'm really excited to see this emerge as an alternative.

My primary interest is having a way to get the most recent version of SQLite installed on installations of Python that might otherwise be lagging behind. It looks like `sqlean.py` gives me SQLite `3.42.0` which is the most recent release!

I do have one problem: I'd like to use this with my Datasette tool, which is often deployed as a public site where anyone can execute SQL queries - e.g. https://latest.datasette.io/fixtures?sql=select+*+from+pragma_function_list%28%29

It looks to me like `sqlean.py` may introduce some functions which are unsafe in that environment. These ones caught my eye:

- `eval()` - can be used for `select eval('create table tmp(value int)');`
- `define()` - this looks like it modifies state as part of a `SELECT`
- `regexp_like()` and friends - do you know if these are susceptible to denial-of-service attacks? Some regular expression implementations are, others are not. https://observablehq.com/@asg017/introducing-sqlite-regex is an example of one that isn't.
- `fileio_read()`, `fileio_write()` etc

Would it be possible to provide either a version of `sqlean.py` that only bundled "safe" functions (safe to be executed by untrusted users), or provide a mechanism whereby these unsafe functions could be disabled?

I'd love to update Datasette to be able to use `sqlean.py` if it's available, but I need to understand the security implications first.

**Comment by nalgeon** [comment]
Thank you for your interest in the project, Simon! I'd love to see `sqlean.py` used in Datasette.

> regexp_like() and friends - do you know if these are susceptible to denial-of-service attacks?

This particular implementation allows lookarounds and is not guaranteed to run in O(n). So I believe they do.

> Would it be possible to provide either a version of sqlean.py that only bundled "safe" functions (safe to be executed by untrusted users), or provide a mechanism whereby these unsafe functions could be disabled?

Implementation-wise, the easiest way is probably to rely on env variables:

- All extensions are enabled by default.
- You can disable some (or all) of them by setting specific env variables in your Python environment.

For example, by setting the following:

```
export SQLEAN_ENABLE_DEFINE=0
export SQLEAN_ENABLE_FILEIO=0
```

You disable the `define` and `fileio` extensions.

What do you think?

**Comment by simonw** [comment]
Yeah that could work - presumably I would need to set those environment variables in Python code before importing the module?

**Comment by simonw** [comment]
To be honest though for Datasette projects it would probably make more sense to have a sqlean just with "safe" functions bundled, and then show people how to use the load extension mechanism to add extra extensions that make sense for their project.

Users with Datasette authentication configured might be very happy to run some of the "dangerous" ones.

**Comment by nalgeon** [comment]
Sorry, not sure I follow. I'm looking at the [code](https://github.com/simonw/datasette/blob/main/datasette/utils/sqlite.py) now:

```python
try:
    import pysqlite3 as sqlite3

    using_pysqlite3 = True
except ImportError:
    import sqlite3
```

Here is how to disable some extensions using the env variable approach:

```python
try:
    os.environ["SQLEAN_ENABLE_DEFINE"] = "0"
    os.environ["SQLEAN_ENABLE_FILEIO"] = "0"

    import sqlean as sqlite3

    using_pysqlite3 = True
except ImportError:
    import sqlite3
```

It is completely transparent to the end user, providing only the "safe" extensions. What am I missing here?

**Comment by nalgeon** [comment]
Alternatively, the package may contain two bundles: safe and full.

Then people will either do `import sqlean.full as sqlite3` or `import sqlean.safe as sqlite3`. Datasette will do the latter.

But it will make it impossible to just do `import sqlean`. Also, the package size will increase because it will contain two bundles.

**Comment by nalgeon** [comment]
We can even have a nice Pythonic API without explicitly messing with env variables, like this:

```python
try:
    import sqlean as sqlite3
    sqlean.extensions.disable("define", "fileio", "regexp")

    using_pysqlite3 = True
except ImportError:
    import sqlite3
```

It'll still use env variables, but they'll be hidden behind the API.

I don't see any downside to this approach.

**Comment by asg017** [comment]
One option is to include different "entrypoints" in the compiled extension. `sqlite-lines` does this here:

https://github.com/asg017/sqlite-lines/blob/main/sqlite-lines.c#L539-L595

There are two entrypoints here: `sqlite3_lines_init` and `sqlite3_lines_no_read_init`. The default entrypoint is `sqlite3_lines_init`, which contains a SQL function that reads files (`lines_read()`). Then `sqlite3_lines_no_read_init` is another opt-in entrypoint that doesn't load in the `lines_read()` function. 

In Python you can specify which entrypoint to use:

```python
import sqlite3
db = sqlite3.connect(":memory:")
db.load_extension("./lines0") # uses default "sqlite3_lines_init" entrypoint
db.load_extension("./lines0", entrypoint="sqlite3_lines_no_read_init") # uses "sqlite3_lines_no_read_init" entrypoint
```

Here's the [sqlite-lines Python bindings](https://github.com/asg017/sqlite-lines/blob/85af492edbd485e91603f759f48f9ec9abd6c28f/python/sqlite_lines/sqlite_lines/__init__.py#L12-L16) that expose a `load()` function that loads the full extension by default, and `load_no_read()` function that loads the safe version. 


But I'm not entirely sure how it would work in `sqlean.py`. I could see multiple entrypoints in the underyling `sqlean.dylib` extension, but since `sqlean.py` statically links a new fresh sqlite3 lib, might be tricky to expose it on a higher level

**Comment by simonw** [comment]
> Alternatively, the package may contain two bundles: safe and full.
> 
> Then people will either do `import sqlean.full as sqlite3` or `import sqlean.safe as sqlite3`. Datasette will do the latter.
> 
> But it will make it impossible to just do `import sqlean`. Also, the package size will increase because it will contain two bundles.

One way to avoid that could be to ship two libraries to PyPI - `sqlean.py` and `sqlean-safe`. Datasette could depend on the latter.

The environment variable thing might work. I'm a bit nervous about it because I want users to be able to opt-in to the full version if they like, at which point I guess I tell them to set their own environment variables and have Datasette learn not to set further variables that conflict with those.

**Comment by simonw** [comment]
This came up for me again today while looking at these two issues:
- https://github.com/simonw/llm/issues/60
- https://github.com/simonw/sqlite-utils/issues/235
In both cases the root problem is that the `sqlite3` that comes bundled with Python3 on macOS has a key feature disabled in it.

I'd like to be able to tell users who encounter that problem that they can `pip install pysqlite3-binary` to work around it - but `pysqlite3-binary` doesn't have macOS wheels available on PyPI.

`sqlean.py` DOES have those wheels, and if it was "safe" by default it would be an easy workaround to tell people to install that (after teaching `sqlite-utils` and `datasette` how to load it if it's available). But without the safe version I'm hesitant to suggest it, just in case people get themselves into a pickle later on.

To be honest, for my tools that use `sqlite-utils` that's not actually a concern - it's only Datasette that can be used to run a web server that allows untrusted users to execute SQL. So maybe I can go ahead and add `sqlean.py` support to `sqlite-utils` as-is today.

**Comment by simonw** [comment]
I guess really what I'm hoping for here is a version of `pysqlite3-binary` that installs cleanly on macOS - filed a related issue here:
- https://github.com/coleifer/pysqlite3/issues/57

**Comment by nalgeon** [comment]
If what you need for Datasette is a "clean" sqlite3 replacement without _any_ extensions (but with `load_extension` enabled) — it's only logical to use `pysqlite3-binary` and not `sqlean.py`. But the maintainer has already rejected your issue, and it's not the first time they've done this — I've seen a similar proposal rejected by them before.

Creating a separate package is something I'd like to avoid at all costs.

What I can do, however, is to disable _all_ extensions by default and make them opt-in like this:

```py
import sqlean
sqlean.extensions.enable_all()
# or
sqlean.extensions.enable("math", "text", "regexp")
```

I'm not super happy with the opt-in approach, but if it works for Datasette, I'd rather do that than create a separate package.

**Comment by simonw** [comment]
That would work brilliantly for me.

**Comment by simonw** [comment]
At what point would calling `sqlean.extensions.enable_all()` have effect? Would it impact only connections created after that method had been called?

Datasette has this plugin hook: https://docs.datasette.io/en/stable/plugin_hooks.html#prepare-connection-conn-database-datasette

```python
@hookimpl
def prepare_connection(conn):
    # Do stuff with conn
````
I'd like to be able to have plugins that enable those features. Maybe that would look something like this?

```python
import sqlean

@hookimpl
def prepare_connection(conn):
    conn.load_extension(sqlean.path_to_extension("regexp"))
```

**Comment by simonw** [comment]
I have a branch of `sqlite-utils` that can use `sqlean` here: https://github.com/simonw/sqlite-utils/tree/sqlean

I successfully used it to solve a `sqlite3.OperationalError: table sqlite_master may not be modified` error in `llm` - details in this comment: https://github.com/simonw/llm/issues/60#issuecomment-1604530997

**Comment by nalgeon** [comment]
> At what point would calling `sqlean.extensions.enable_all()` have effect? Would it impact only connections created after that method had been called?

It would affect all connections created in the same Python process after this call.

> I'd like to be able to have plugins that enable those features. Maybe that would look something like this?

Unfortunately, it would not work. If there is a connection object, all enabled extensions are already loaded. There is no way to load them for the specific connection afterwards like `conn.load_extension()` does.

To enable a different set of extensions for a particular plugin, it must somehow call `sqlean.extensions.enable()` just before the connection is created. And restore the previous state after the connection is created. Which is probably clumsy and undesirable.

**Comment by simonw** [comment]
I might be able to use my `startup()` plugin hook for that: https://docs.datasette.io/en/stable/plugin_hooks.html#startup-datasette

Presumably I could still use `sqlean` without extensions and then use `conn.load_extension()` against compiled versions of the extensions, e.g. `regexp.dylib` from the `sqlean-macos-arm64.zip` file on https://github.com/nalgeon/sqlean/releases/tag/0.21.5

Really what I'm looking for here is a reliable way to get a modern version of SQLite with the ability to load extensions in a way that's easy for my Mac users to install without having to run a compiler.

**Comment by nalgeon** [comment]
> Presumably I could still use sqlean without extensions and then use conn.load_extension() against compiled versions of the extensions

Sure, you can do that.

OK, so it's settled then? Should I release a version of `sqlean.py` with extensions disabled by default and an opt-in mechanism?

**Comment by simonw** [comment]
Have you considered a Python package for your extensions that works like these ones by @asg017 ?

- https://pypi.org/project/sqlite-http/#files
- https://pypi.org/project/sqlite-lines/#files
- etc

Docs here: https://github.com/asg017/sqlite-http/blob/main/python/sqlite_http/README.md

They let you do this in code:
```python
import sqlite_http
print(sqlite_http.loadable_http())
# '/.../venv/lib/python3.9/site-packages/sqlite_http/http0'

import sqlite3
conn = sqlite3.connect(':memory:')
sqlite_http.load(conn)
conn.execute('select http_version()').fetchone()
```

**Comment by simonw** [comment]
> OK, so it's settled then? Should I release a version of `sqlean.py` with extensions disabled by default and an opt-in mechanism?

Huge +1 from me on that plan!

**Comment by nalgeon** [comment]
Implemented in [0.21.5.1](https://github.com/nalgeon/sqlean.py/releases/0.21.5.1). All extensions are disabled by default and can be enabled with `sqlean.extensions.enable_all()` or `sqlean.extensions.enable(*names)`.

**Comment by simonw** [comment]
`sqlite-utils` 3.33 is released, and it now uses `sqlean.py` if it is installed in the same virtual environment: https://sqlite-utils.datasette.io/en/stable/changelog.html#v3-33

This has helped resolve a bunch of issues, most notably this one:

 - https://github.com/simonw/sqlite-utils/issues/235#issuecomment-1606415188

**Comment by nalgeon** [comment]
Okay, since there are no more questions, I'll close this. To install extensions, you might want to check out the [sqlpkg](https://github.com/nalgeon/sqlpkg-cli) package manager.
